version: "3"


services:
  web_alvin:
    container_name: web_alvin
    build:
      context: .
#    ports:
#      - "8081:8081"
    volumes:
      - .:/usr/src/backend/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_alvin.rule=Host(`alvinandpartners.com`)"
      - "traefik.http.routers.web_alvin.entrypoints=websecure"
      - "traefik.http.routers.web_alvin.tls=true"
      - "traefik.http.routers.web_alvin.tls.certresolver=production"
    networks:
        - main_host
networks:
  main_host:
    external: true