version: "3"


services:
  web:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/backend/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`alvinandpartners.com `)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=production"
    networks:
        - main_host
networks:
  main_host:
    external: true