# Generated by Django 4.2.14 on 2024-08-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_banner',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_details',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_surmmary',
        ),
    ]
