# Generated by Django 4.2.14 on 2024-08-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('service', '0002_remove_service_service_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_banner',
            field=models.ForeignKey(blank=True, help_text='Best size for this image will be 1400x400', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_details',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_surmmary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
