# Generated by Django 4.2.14 on 2024-08-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('service', '0004_remove_service_service_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_details',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_summary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
