# Generated by Django 4.2.14 on 2024-08-03 12:09

from django.db import migrations
import streams.block
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_service_details_service_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_details',
            field=wagtail.fields.StreamField([('details', streams.block.RichtextBlock())], blank=True, null=True),
        ),
    ]
