# Generated by Django 4.2.14 on 2024-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quotation_doc',
            field=models.FileField(null=True, upload_to='document'),
        ),
    ]
