# Generated by Django 4.2.14 on 2024-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_quotation_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quotation_pdf',
            field=models.FileField(null=True, upload_to='document'),
        ),
    ]
