# Generated by Django 4.2.14 on 2024-08-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_service_quotation_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='quotation_doc',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='service',
            name='quotation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
    ]
