# Generated by Django 5.0.6 on 2024-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_sub_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
