# Generated by Django 5.0.7 on 2024-07-23 20:17

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.AddField(
            model_name='homepage',
            name='team',
            field=wagtail.fields.StreamField([('Team', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=40, required=True)), ('name', wagtail.blocks.TextBlock(max_length=200, required=True)), ('facebook', wagtail.blocks.URLBlock(help_text='Enter the link to facebook.', required=False)), ('instagram', wagtail.blocks.URLBlock(help_text='Enter link to instagram', required=False)), ('linkedin', wagtail.blocks.URLBlock(help_text='Enter link to linkedin', required=False))])))]))], blank=True, null=True),
        ),
    ]
