# Generated by Django 5.0.7 on 2024-07-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_content_homepage_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='team',
            new_name='content',
        ),
    ]
