# Generated by Django 5.0.7 on 2024-07-24 17:51

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_team_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_information',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('Staff', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=40, required=True)), ('name', wagtail.blocks.TextBlock(max_length=200, required=True)), ('facebook', wagtail.blocks.URLBlock(help_text='Enter the link to facebook.', required=False)), ('instagram', wagtail.blocks.URLBlock(help_text='Enter link to instagram', required=False)), ('linkedin', wagtail.blocks.URLBlock(help_text='Enter link to linkedin', required=False))])))]))], blank=True, null=True),
        ),
    ]
