# Generated by Django 5.0.7 on 2024-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_about_information_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_information',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
