# Generated by Django 5.0.7 on 2024-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_about_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
