# Generated by Django 4.2.14 on 2024-08-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
