# Generated by Django 4.2.14 on 2024-08-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_company_achievements',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
