# Generated by Django 4.2.14 on 2024-08-05 09:17

from django.db import migrations
import streams.block
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_information',
            field=wagtail.fields.StreamField([('details', streams.block.RichtextBlock())], null=True),
        ),
    ]
