# Generated by Django 4.2.14 on 2024-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homepage_happy_clients_homepage_hard_workers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='happy_clients',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hard_workers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='project',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='support_hours',
            field=models.IntegerField(null=True),
        ),
    ]
