# Generated by Django 4.2.14 on 2024-08-09 08:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_homepage_happy_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonial',
            field=wagtail.fields.StreamField([('testimonials', wagtail.blocks.StructBlock([('clients_testimony', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=40, required=True)), ('name', wagtail.blocks.TextBlock(max_length=200, required=True)), ('testimony', wagtail.blocks.TextBlock(max_length=200, required=True))])))]))], blank=True, null=True),
        ),
    ]
