# Generated by Django 4.2.14 on 2024-08-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_homepage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='happy_clients',
            new_name='happy_clients_number',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='project',
            new_name='projects_number',
        ),
    ]
