# Generated by Django 4.2.14 on 2024-08-04 19:26

from django.db import migrations
import streams.block
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_portfolio_service_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='project_galley',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service_details',
            field=wagtail.fields.StreamField([('details', streams.block.RichtextBlock()), ('project_photos', wagtail.blocks.StructBlock([('photos', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
