# Generated by Django 4.2.14 on 2024-08-04 19:46

from django.db import migrations
import streams.block
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_remove_portfolio_project_galley_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_galley',
            field=wagtail.fields.StreamField([('photo', wagtail.blocks.StructBlock([('photos', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service_details',
            field=wagtail.fields.StreamField([('details', streams.block.RichtextBlock())], blank=True, null=True),
        ),
    ]
