# Generated by Django 4.2.14 on 2024-08-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_portfolio_project_galley_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='service_details',
            new_name='project_details',
        ),
    ]
