# Generated by Django 4.2.14 on 2024-08-04 19:52

from django.db import migrations
import streams.block
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_rename_service_details_portfolio_project_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_details',
            field=wagtail.fields.StreamField([('details', streams.block.RichtextBlock())], null=True),
        ),
    ]
