# Generated by Django 4.2.14 on 2024-08-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_portfolio_project_url_portfolio_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_category',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_client',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_date',
            field=models.DateField(max_length=5000, null=True),
        ),
    ]
