# Generated by Django 4.2.14 on 2024-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_alter_portfolio_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_URL',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
